<div id="fotter">
  <div class="fotter_links">
    <div align="center"><a id="footnav_home" href="/" class="fotterlink">Home</a>  |  <a id="footnav_register" href="/register.php" class="fotterlink">Register</a>  |  <a id="footnav_about" href="/about.php" class="fotterlink">About Us</a>  |  <a id="footnav_faq" href="/faq.php" class="fotterlink">FAQ</a>  |  <a id="footnav_tos" href="/tos.php" class="fotterlink">Terms of Service</a>  |  <a id="footnav_contact" href="/contact.php" class="fotterlink">Contact Us</a></div>
  </div>
  <div class="fotter_copyrights">
    <div align="center">&copy; 2011 Frontier Digital, LLC. All Rights Reserved</div>
    <div id="version" align="center"><?php echo $GLOBALS['version']; ?></div>
  </div>
  <div class="fotter_designed">
    <div align="center">Template By : <a href="http://www.templateworld.com/" class="fotter_designedlink">Template World</a></div>
  </div>
</div>
<script type="text/javascript">
    mpmetrics.track_links("#footnav_home", "footnav click", {"type": "home"});
    mpmetrics.track_links("#footnav_register", "footnav click", {"type": "register"});
    mpmetrics.track_links("#footnav_about", "footnav click", {"type": "about"});
    mpmetrics.track_links("#footnav_faq", "footnav click", {"type": "faq"});
    mpmetrics.track_links("#footnav_tos", "footnav click", {"type": "tos"});
    mpmetrics.track_links("#footnav_contact", "footnav click", {"type": "contact"});
</script>

