<div id="fotter">
  <div class="fotter_links">
    <div align="center"><a id="footnav_home" href="/" class="fotterlink">Home</a>  |  <a id="footnav_register" href="/register.php" class="fotterlink">Register</a>  |  <a id="footnav_about" href="/about.php" class="fotterlink">About Us</a>  |  <a id="footnav_faq" href="/faq.php" class="fotterlink">FAQ</a>  |  <a id="footnav_tos" href="/tos.php" class="fotterlink">Terms of Service</a>  |  <a id="footnav_contact" href="/contact.php" class="fotterlink">Contact Us</a></div>
  </div>
  <div class="fotter_copyrights">
    <div align="center"><?php echo $GLOBALS['footer_copyright'] ?></div>
    <div id="version" align="center">
        <a href="https://plus.google.com/107079019841451172444?prsrc=3" style="cursor:pointer;display:inline-block;text-decoration:none;color:#333;font:13px/16px arial,sans-serif;">
            <span style="display:inline-block;vertical-align:top;margin-right:5px;">FrameAlbum on</span>
            <img src="https://ssl.gstatic.com/images/icons/gplus-16.png" alt="Google+ Icon" style="border:0;width:16px;height:16px;"/>
        </a>
        <?php echo $GLOBALS['version']; ?>
    </div>
  </div>
  <div class="fotter_designed">
    <div align="center">Designed By : <a href="#" class="fotter_designedlink">Template World</a> | <a href="http://mixpanel.com/f/partner"><img src="http://mixpanel.com/site_media/images/partner/badge_light.png" alt="Web Analytics" /></a></div>
  </div>
</div>
<script type="text/javascript">
    mpmetrics.track_links("#footnav_home", "footnav click", {"type": "home"});
    mpmetrics.track_links("#footnav_register", "footnav click", {"type": "register"});
    mpmetrics.track_links("#footnav_about", "footnav click", {"type": "about"});
    mpmetrics.track_links("#footnav_faq", "footnav click", {"type": "faq"});;
    mpmetrics.track_links("#footnav_tos", "footnav click", {"type": "tos"});
    mpmetrics.track_links("#footnav_contact", "footnav click", {"type": "contact"});
</script>

